### PR TITLE
Feature/test improvements

### PR DESCRIPTION
**Pull request by maschmann**
* complete the component factory test
* add some eyecandy about code quality and testing

### CODE REVIEW

**Comment by maschmann** [comment]
Open tasks:
- [ ] abstract test file access with vfs
- [ ] finish graph tests @ 100%

**Comment by tigitz** [comment]
@maschmann I suggest we should have some coding standards on the testing side of the project.
I'm thinking of:

- Use `::class` for FQCN
- Use `$this->expectException()`
- Bootstrap dependencies of the tested class in the `setUp` method as much as possible
- Use the `expects()` method while mocking to ensure the right expected method behavior

WDYT ?

**Comment by maschmann** [comment]
Thank you for the suggestions!

* ::class -> agreed, doing that @work already, haven't rolled out to my other projects, yet
* Exceptions: Why not use the annotation? Any downsides I don't know of?
* Bootstrapping: I'd prefer doing most stuff "fresh" for every test to have a clear state. Exceptions are highly complex classes like network or graph where a specific state is needed for testing. For common testing ground, an abstraction layer for the phpunit test base class should be introduced, to ease the later transition to phpunit 6 where namespacing comes into play
* "expects" -> When I do the next transition of phpflo repos, I will move a lot of interfaces and helper classes around. This will at least mean another "common" lib for all repos where the interface and test baseclasses are located. There will also be the [StubTrait](https://github.com/phpflo/phpflo-core/blob/master/lib/PhpFlo/Test/StubTrait.php) for unified mocking - I think this will help increase the test writing speed.

I'd add:
* don't assertInstanceOf() concrete implementations when an according interface is at hand (ComponentInterface e.g.)

**Comment by tigitz** [comment]
> Exceptions: Why not use the annotation? Any downsides I don't know of?

Yes indeed : https://thephp.cc/news/2016/02/questioning-phpunit-best-practices

> Bootstrapping: I'd prefer doing most stuff "fresh" for every test to have a clear state.

`setUp` is actually always run fresh before a test but you're right, extracting the bootstraping logic into their own class which we would be able to extend or statically call would lead to a single point of modification if tested class behavior changes.

> "expects" 

I'm not sure I understand you correctly on this one, my point was to always use the `->expects()` method when mocking the behavior of a mock class. But I get what you meant and I agree.

> don't assertInstanceOf() concrete implementations when an according interface is at hand (ComponentInterface e.g.)

Yes, as a golden rule, mock the tested class dependencies as much as possible.

**Comment by maschmann** [comment]
@tigitz I agree on the expectedException() part and will refactor accordingly.
Next steps will be closing/merging this PR and moving phpflo into a monorepo with separate (readonly) component repos. This will allow a "phpflo-common" repo to encapsulate testing classes and ease dependency management.

**Pull request merged**
